//
//  MUColor.m
//  MeetupApp
//
//  Generated by Meetup Design on 09/11/2015.
//  Copyright (c) 2015 Meetup, Inc. All rights reserved.
//

#import "MUColor.h"
@implementation MUColor

#pragma mark - Base color palette

+ (UIColor *)whiteColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)darkGrayColor {
    return [UIColor colorWithRed:0.208f green:0.243f blue:0.282f alpha:1.0f];
}

+ (UIColor *)mediumGrayColor {
    return [UIColor colorWithRed:0.902f green:0.914f blue:0.925f alpha:1.0f];
}

+ (UIColor *)lightGrayColor {
    return [UIColor colorWithRed:0.953f green:0.965f blue:0.976f alpha:1.0f];
}

+ (UIColor *)redColor {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)greenColor {
    return [UIColor colorWithRed:0.384f green:0.675f blue:0.459f alpha:1.0f];
}

+ (UIColor *)blueColor {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}

+ (UIColor *)lightBlueColor {
    return [UIColor colorWithRed:0.408f green:0.647f blue:0.851f alpha:1.0f];
}

+ (UIColor *)purpleColor {
    return [UIColor colorWithRed:0.443f green:0.376f blue:0.667f alpha:1.0f];
}

+ (UIColor *)brownColor {
    return [UIColor colorWithRed:0.443f green:0.247f blue:0.098f alpha:1.0f];
}

+ (UIColor *)yellowColor {
    return [UIColor colorWithRed:0.941f green:0.796f blue:0.31f alpha:1.0f];
}



#pragma mark - Text colors

+ (UIColor *)textPrimaryColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.87f];
}

+ (UIColor *)textSecondaryColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.54f];
}

+ (UIColor *)textTertiaryColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.26f];
}

+ (UIColor *)textPrimaryInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)textSecondaryInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.7f];
}

+ (UIColor *)textTertiaryInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.3f];
}



#pragma mark - UI Colors

+ (UIColor *)accentColor {
    return [UIColor colorWithRed:0.886f green:0.216f blue:0.235f alpha:1.0f];
}

+ (UIColor *)linkColor {
    return [UIColor colorWithRed:0.224f green:0.529f blue:0.796f alpha:1.0f];
}

+ (UIColor *)borderColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.12f];
}

+ (UIColor *)borderInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.2f];
}

+ (UIColor *)overlayPressedColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.1f];
}

+ (UIColor *)modalShadeColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.75f];
}

+ (UIColor *)shadeColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.05f];
}

+ (UIColor *)shadeInvertedColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.1f];
}

+ (UIColor *)textProtectionColor {
    return [UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.05f];
}



#pragma mark - Background colors

+ (UIColor *)contentBGColor {
    return [UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f];
}

+ (UIColor *)contentBGInvertedColor {
    return [UIColor colorWithRed:0.208f green:0.243f blue:0.282f alpha:1.0f];
}

+ (UIColor *)collectionBGDarkColor {
    return [UIColor colorWithRed:0.902f green:0.914f blue:0.925f alpha:1.0f];
}

+ (UIColor *)collectionBGLightColor {
    return [UIColor colorWithRed:0.953f green:0.965f blue:0.976f alpha:1.0f];
}



#pragma mark - EXTERNAL

+ (UIColor *)facebookColor {
    return [UIColor colorWithRed:0.231f green:0.349f blue:0.596f alpha:1.0f];
}

+ (UIColor *)twitterColor {
    return [UIColor colorWithRed:0.2f green:0.8f blue:1.0f alpha:1.0f];
}

+ (UIColor *)linkedinColor {
    return [UIColor colorWithRed:0.282f green:0.459f blue:0.706f alpha:1.0f];
}

+ (UIColor *)tumblrColor {
    return [UIColor colorWithRed:0.169f green:0.286f blue:0.392f alpha:1.0f];
}

+ (UIColor *)flickrColor {
    return [UIColor colorWithRed:0.996f green:0.031f blue:0.514f alpha:1.0f];
}

+ (UIColor *)foursquareColor {
    return [UIColor colorWithRed:0.047f green:0.729f blue:0.875f alpha:1.0f];
}

+ (UIColor *)googleplusColor {
    return [UIColor colorWithRed:0.776f green:0.239f blue:0.176f alpha:1.0f];
}

+ (UIColor *)instagramColor {
    return [UIColor colorWithRed:0.306f green:0.263f blue:0.235f alpha:1.0f];
}

+ (UIColor *)redditColor {
    return [UIColor colorWithRed:0.808f green:0.89f blue:0.973f alpha:1.0f];
}

+ (UIColor *)wepayColor {
    return [UIColor colorWithRed:0.282f green:0.569f blue:0.863f alpha:1.0f];
}

+ (UIColor *)yahooColor {
    return [UIColor colorWithRed:0.482f green:0.0f blue:0.6f alpha:1.0f];
}



@end
