//
//  MUColor.h
//  MeetupApp
//
//  Generated by Meetup Design on 09/11/2015.
//  Copyright (c) 2015 Meetup, Inc. All rights reserved.
//

@import UIKit;
@interface MUColor : NSObject

#pragma mark - Base color palette

+ (UIColor *)whiteColor;
+ (UIColor *)darkGrayColor;
+ (UIColor *)mediumGrayColor;
+ (UIColor *)lightGrayColor;
+ (UIColor *)redColor;
+ (UIColor *)greenColor;
+ (UIColor *)blueColor;
+ (UIColor *)lightBlueColor;
+ (UIColor *)purpleColor;
+ (UIColor *)brownColor;
+ (UIColor *)yellowColor;


#pragma mark - Text colors

+ (UIColor *)textPrimaryColor;
+ (UIColor *)textSecondaryColor;
+ (UIColor *)textTertiaryColor;
+ (UIColor *)textPrimaryInvertedColor;
+ (UIColor *)textSecondaryInvertedColor;
+ (UIColor *)textTertiaryInvertedColor;


#pragma mark - UI Colors

+ (UIColor *)accentColor;
+ (UIColor *)linkColor;
+ (UIColor *)borderColor;
+ (UIColor *)borderInvertedColor;
+ (UIColor *)overlayPressedColor;
+ (UIColor *)modalShadeColor;
+ (UIColor *)shadeColor;
+ (UIColor *)shadeInvertedColor;
+ (UIColor *)textProtectionColor;


#pragma mark - Background colors

+ (UIColor *)contentBGColor;
+ (UIColor *)contentBGInvertedColor;
+ (UIColor *)collectionBGDarkColor;
+ (UIColor *)collectionBGLightColor;


#pragma mark - EXTERNAL

+ (UIColor *)facebookColor;
+ (UIColor *)twitterColor;
+ (UIColor *)linkedinColor;
+ (UIColor *)tumblrColor;
+ (UIColor *)flickrColor;
+ (UIColor *)foursquareColor;
+ (UIColor *)googleplusColor;
+ (UIColor *)instagramColor;
+ (UIColor *)redditColor;
+ (UIColor *)wepayColor;
+ (UIColor *)yahooColor;


@end
